### ISSUE TITLE
Error when running migration

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [grimzy/laravel-mysql-spatial#1]
Hi, thanks by this awesome library. I'm trying it, but when I attempt to run a migration, this returns:

[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to CreateStoresTable::{closure}() must be an instance of Grimzy\LaravelMysqlSpatial\Schema\Blueprint, instance of Ill
  uminate\Database\Schema\Blueprint given, called in ...

I've imported the Grimzy\LaravelMysqlSpatial\Schema\Blueprint inside the migration, but this not runs.

Thanks by Help

**Comment by grimzy** [comment]
Have you registered `Grimzy\LaravelMysqlSpatial\SpatialServiceProvider` in your `config/app.php`?

Also, if the service provider is loaded, you should be able to use the standard `Illuminate\Database\Schema\Blueprint` in your migrations. I use `Grimzy\LaravelMysqlSpatial\Schema\Blueprint` just for autocomplete in my IDE.

**Comment by deividaspetraitis** [comment]
Mostly you need to bind new `Blueprint` object manually and I haven't saw that is done package level so not sure about PR. Please see workaround how to bind it manually in migration file: https://gist.github.com/deividaspetraitis/3ad70f935ed4184327e2320a3c038a90
