### ISSUE TITLE
Use Laravel Collections instead of arrays in Geometries[]

### ISSUE THREAD

**Issue by grimzy** [grimzy/laravel-mysql-spatial#10]
Including PointCollection and GeometryCollection

**Comment by a-komarev** [comment]
What benefits developers will get from it?

**Comment by grimzy** [comment]
@a-komarev, I was thinking of using `Collection` to avoid reinventing the wheel for the implementations of `IteratorAggregate`, `ArrayAccess`, `Countable`, `Arrayable`, `Jsonable` (i.e. in `PointCollection`). 
Also, to make available some of the useful helpers provided with `Collection` with spatial collections. 

But now, I'm thinking that most of these helpers will need to be overridden to function so it's probably cleaner to just implement those interfaces in `PointCollection`, `MultiLineString`, `MultiPolygon`, and `GeometryCollection` (https://github.com/grimzy/laravel-mysql-spatial/issues/15).

And if `Collection` functionalities are needed, one can just do something like:
```
collect($pointCollection->toArray())
```

**Comment by a-komarev** [comment]
Did you think about extending collection class?

**Comment by grimzy** [comment]
Yes, but I'm not sure how this would be implemented.

I'm closing this in favor of #19.
