### ISSUE TITLE
Tip to get filtered Places by KM

### ISSUE THREAD

**Issue by fredroo** [grimzy/laravel-mysql-spatial#106]
How I can filter items by KM

E.G: get items at distance 3KM radius from an origin point

My code so far

`       

        $origin = Place::first();

        $lat = $origin->location->getLat();

        $lng = $origin->location->getLng();

        $point = new Point($lat, $lng);

        $distance = 3;

        $places = Place::distanceExcludingSelf('location', $point, $distance)->get();

        return response($places);
`

But not works well way now

**Comment by fredroo** [comment]
@grimzy can you help me, please?

**Comment by fredroo** [comment]
@ajthinking can you help me, please?

**Comment by ajthinking** [comment]
Syntax looks right to me. Do you get an error?

Distance probably in meters right? So you are searching in a 3 meter radius which a bit small.

**Comment by fredroo** [comment]
@ajthinking No errors, but returned Places with distances more than 3 KM (3 thousand meters) from the origin point

**Comment by fredroo** [comment]
@ajthinking I think can be because I am using MariaDB instead of Mysql 5.7

What do you think?

**Comment by ajthinking** [comment]
Maybe because your points are in lat/long? Then "3" translates to a lot further distance ~: https://www.google.com/search?q=3+degrees+to+meter&oq=3+degrees+to+meter&aqs=chrome..69i57j0l5.8599j0j7&sourceid=chrome&ie=UTF-8

Im assuming `distanceSphereExcludingSelf` is used to solve that problem

**Comment by fredroo** [comment]
@ajthinking
That's I was thinking, but only works with Mysql 5.7.6, I will be testing with Mysql 5.7.6

function st_distance_sphere is required, but MariaDB still don't have this function

https://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html

https://mariadb.com/kb/en/library/mysqlmariadb-spatial-support-matrix/

Thanks a lot

**Comment by fredroo** [comment]
Solved!

Now I am using Mysql 5.7.27

```
        $origin = Place::first();
        $lat = $origin->location->getLat();
        $lng = $origin->location->getLng();

        $point = new Point($lat, $lng);

        $distance = 50000; // 50KM in meters

        $places = Place::distanceSphereExcludingSelf('location', $point, $distance)->get();

        return response($places);
```
