### ISSUE TITLE
Problem creating Linestring

### ISSUE THREAD

**Issue by awurman** [grimzy/laravel-mysql-spatial#116]
Hi! i view similar problems but i cant resolve it... any clue? thanks!

        $arrayline =  [new Point(40.74894149554006, -73.98615270853043),
                       new Point(40.74848633046773, -73.98648262023926),
                       new Point(40.747925497790725, -73.9851602911949),
                       new Point(40.74837050671544, -73.98482501506805),
                       new Point(40.74894149554006, -73.98615270853043)];

        $collection = new LineString($arrayline);

In this line i have message: "Argument 1 passed to GeoJson\Geometry\Point::__construct() must be of the type array, object given, called in C:\wamp64\www\lanube\vendor\jmikola\geojson\src\GeoJson\Geometry\MultiPoint.php on line 28"

**Comment by grimzy** [comment]
Can't really help without more context especially because this is unrelated to my package. The code you presented is from `jmikola\geojson`. Maybe you're using the Geometries under `GeoJson\Geometry` instead of the ones under `Grimzy\LaravelMysqlSpatial\Types` ?

Closing ticket.
