### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by crynobone** [grimzy/laravel-mysql-spatial#124]
Laravel 7 will be released today, would be great if we can have support for it soon.

https://laravel.com/docs/master/releases#support-policy

**Comment by heikokrebs** [comment]
Yeah would be great if we could get this merged!

**Comment by mjbonanno** [comment]
This is currently my own setback from upgrading.

**Comment by grimzy** [comment]
Cheers, thanks!

I'll have this released later today.

**Comment by heikokrebs** [comment]
@grimzy that would be awesome!

**Comment by grimzy** [comment]
There we go: https://github.com/grimzy/laravel-mysql-spatial/releases/tag/2.2.1

**Comment by heikokrebs** [comment]
@grimzy Thanks a lot!
