### ISSUE TITLE
Unset $offset variable

### ISSUE THREAD

**Issue by a-komarev** [grimzy/laravel-mysql-spatial#13]
https://github.com/grimzy/laravel-mysql-spatial/blob/e17f4915996c8d3c285b9cca310069642593da2a/src/Types/PointCollection.php#L64-L71

**Comment by grimzy** [comment]
That's code that I mistakenly moved from https://github.com/njbarrett/laravel-postgis.

I was thinking about replacing it (https://github.com/grimzy/laravel-mysql-spatial/issues/10) and possibly extending the features from Laravel Collection.

What do you think?
