### ISSUE TITLE
Laravel8 + MySQL 5.7

### ISSUE THREAD

**Issue by Nizari** [grimzy/laravel-mysql-spatial#151]
@grimzy Thank you for your hard work. Any idea when this package wil support laravel8 + mysql 5.7? Or is this already possible.

**Comment by alasdairw** [comment]
I've also just has a problem not being able to install the 2.x branch on Laravel 8 as well.  Would this be complex to support?

**Comment by brysem** [comment]
This would be a very welcome addition. Anything I can do to help make this possible?

**Comment by miclf** [comment]
Same here. Cannot upgrade MySQL for many reasons and, right now, we cannot upgrade to Laravel 8 just because of this package (all our other dependencies now support it). We’ll do our own fork of version `2.2.3` for the time being, but it would be great to keep the ability to use the ‘official’ repository.

**Comment by Nizari** [comment]
@miclf Could you share your solution if you succeed?

**Comment by miclf** [comment]
@Nizari Sure. So far, I did only two things:

1. I allowed Laravel 8 in the list of Composer dependencies, [like this](https://github.com/Liege-bike/laravel-mysql-spatial/commit/f953d02675b98a8288e732ce5cfd6cf8619a465b).
2. Then I changed the visibility of a method that the package was overwriting from Laravel, [like that](https://github.com/Liege-bike/laravel-mysql-spatial/commit/51e5990f20173e3e54d3c7ba465c12b632a03492).

So far, this works for us. But note that we only use a small part of the features that are provided by the package, so there may be additional changes that could be required to make it work in your case.

Also, if you need a fork, please make your own: I cannot guarantee that we will keep our own online, as we may look for an alternative package at some point.

Hope this helps :)

**Comment by Nizari** [comment]
> @Nizari Sure. So far, I did only two things:
> 
> 1. I allowed Laravel 8 in the list of Composer dependencies, [like this](https://github.com/Liege-bike/laravel-mysql-spatial/commit/f953d02675b98a8288e732ce5cfd6cf8619a465b).
> 2. Then I changed the visibility of a method that the package was overwriting from Laravel, [like that](https://github.com/Liege-bike/laravel-mysql-spatial/commit/51e5990f20173e3e54d3c7ba465c12b632a03492).
> 
> So far, this works for us. But note that we only use a small part of the features that are provided by the package, so there may be additional changes that could be required to make it work in your case.
> 
> Also, if you need a fork, please make your own: I cannot guarantee that we will keep our own online, as we may look for an alternative package at some point.
> 
> Hope this helps :)

Thank you very much @miclf. We’ll check it out!

**Comment by shinsenter** [comment]
Please add support for Laravel 8 (https://github.com/Liege-bike/laravel-mysql-spatial/commit/f953d02675b98a8288e732ce5cfd6cf8619a465b)

**Comment by redbastie** [comment]
+1

i created a PR for this: https://github.com/grimzy/laravel-mysql-spatial/pull/155

if you could merge & tag i would hugely appreciate it, as i really need this for a client

**Comment by grimzy** [comment]
Thank you everyone.
Just released [v5.0.0](https://github.com/grimzy/laravel-mysql-spatial/releases/tag/5.0.0) with support for Laravel 8 / MySQL 5.7.

**Comment by brysem** [comment]
> Thank you everyone.
> Just released [v5.0.0](https://github.com/grimzy/laravel-mysql-spatial/releases/tag/5.0.0) with support for Laravel 8 / MySQL 5.7.

Awesome. Thank you very much!

**Comment by Nizari** [comment]
Thank you so much! @grimzy
