### ISSUE TITLE
Inserting LineString

### ISSUE THREAD

**Issue by jacurtis** [grimzy/laravel-mysql-spatial#20]
I am having a terribly difficult time inserting a LineString. Points insert fine, but LineStrings are not being formatted corrected during the insert.

```
$route = new Route();
$route->path = new LineString([new Point(1, 1), new Point(2, 2), new Point(3, 3));
$route->save();
```

This is basically what I am doing. It actually appears that the `LineString()` object is being created successfully, but I just can't get it to insert properly.

If i dump out the `$route->path` property before the insert, this is what the `LineString()` object looks like. (Am I maybe constructing the object wrong?), to me it looks like the object is constructed correct (there are Lat and Lng properties for each point in the list, I just didn't expand them all for brevity).

![image](https://user-images.githubusercontent.com/537329/30894090-d4860a7e-a2fe-11e7-94b7-56adc3b5cbe9.png)

Using this code, the save() method throws a SQL error "Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field."

Basically MySQL is saying it can't figure out how to build the geometry object with the information it is being passed.

Here is the SQL statement being produced:

```
SQL: insert into `routes` (`name`, `type`, `departure_name`, `departure_id`, `arrival_name`, `arrival_id`, `distance`, `duration`, `route`, `polyline`, `updated_at`, `created_at`) values (Route Runner, 1, Leas, 3, Heldj, 2, 36, 44, 40.786159 -111.981999,40.782483 -111.991326,40.777533 -111.99107,40.763445 -111.978736,40.763865 -111.914582,40.782344 -111.908802,40.782438 -111.896401,40.771566 -111.892318,40.771572 -111.899574,40.782391 -111.899599,40.782109 -111.911055,40.760796 -111.914607,40.744019 -111.904332,40.698132 -111.901919,40.611625 -111.906225,40.529731 -111.891577,40.493677 -111.891283,40.458924 -111.914726,40.449055 -111.912245,40.432307 -111.893405, 1, 2017-09-26 21:14:36, 2017-09-26 21:14:36)
```

So the problem is clear to me that the format that the LineString is being inserted is incorrect. It should be `lineString(lat lng, lat lng, lat lng)` instead of just `lat lng, lat lng, lat lng`.

**How am I using this package wrong?**

**Comment by JoeCDNA** [comment]
Is your Model using `SpatialTrait`?

**Comment by grimzy** [comment]
Is you model using `SpatialTrait`?

**Comment by jacurtis** [comment]
That was the problem. I actually did that on the other model which was storing `Point()`s and then I forgot to add it to this model. Thanks.
