### ISSUE TITLE
Use Point class in Model

### ISSUE THREAD

**Issue by onslauth** [grimzy/laravel-mysql-spatial#21]
Hi,

I have implemented this extension, and have managed to get most of it working. I would like to now use the Point object inside the Model. Essentially I would like to set an attribute value, so something like:
$this->attributes[ "location" ] = new Point( $lat, $lng );

However, the Point class is not available inside of the model. Is there a way to do this?

**Comment by binmosa** [comment]
@onslauth if I understand your question, then you only need to import the class in that model, then it should works.  try to write (at the top of your model) this :

`use Grimzy\LaravelMysqlSpatial\Types\Point;
`
then the type Point will be available.

**Comment by onslauth** [comment]
Hi,

Thanks for the answer. I actually found it after I started to look through the unit tests. Perhaps this should be part of the readme?

Thanks for the help.
