### ISSUE TITLE
Add Geometry::fromJson($geoJson)

### ISSUE THREAD

**Issue by grimzy** [grimzy/laravel-mysql-spatial#23]
To complete API with `JsonSerializable`

**Comment by saintplay** [comment]
Thanks for this awesome package, hopefully we can see this feature soon, it will be available for all version of mysql?

**Comment by grimzy** [comment]
I haven't had a lot of time to work on this package recently but planing to resume the development of this feature in January 2018.
And yes, this feature should be available for MySQL 5.5+ (I'll be 100% sure after writing/running the tests).

Any suggestions regargind the implementation? You can already look at the [`from-geojson`](https://github.com/grimzy/laravel-mysql-spatial/tree/from-geojson) branch.
