### ISSUE TITLE
Select polygon from DB

### ISSUE THREAD

**Issue by llioor** [grimzy/laravel-mysql-spatial#30]
I have an issue to pass the polygon data from DB to Client.
I save the polygon like this:

```
// Save item
$item = new Item($data);
...
$item->polygon = $this->buildPolygonFromArray($data['polygon']);
$item->save();

// Build polygon from array
use Grimzy\LaravelMysqlSpatial\Types\LineString;
use Grimzy\LaravelMysqlSpatial\Types\Point;
use Grimzy\LaravelMysqlSpatial\Types\Polygon;

private function buildPolygonFromArray($polygon) {
        $points = $polygon['coordinates'][0];
        $arrayOfPoints = [];
        foreach ($points as $point) {
            $arrayOfPoints[] = new Point($point[0], $point[1]);
        }
        $lineString = new LineString($arrayOfPoints);
        return new Polygon([$lineString]);
    }
```

Now the polygon is been selected automatically by laravel and passed to the client BUT the problem is that the latitude and longitude are been switched in positions.
I send this array with lat&long points:
```
'polygon' =>
                [
                    'coordinates' =>
                        [
                            0 => [
                                [34.783342, 32.075312],
                                [34.782876, 32.075323],
                                [34.782862, 32.074953],
                                [34.783407, 32.07494],
                                [34.783342, 32.075312],
                            ],
                        ]
                ]
```
On DB it's been saved on the opposite way (long&lat) because of the `Point()->toPair()` function but it is totally OK. The problem is with the select and passing to client.

The response I get in the network is like this:
`{"type":"Polygon","coordinates":[[[32.075312,34.783342],[32.075323,34.782876],[32.074953,34.782862],[32.07494,34.783407],[32.075312,34.783342]]]}`

When I'm going over the array the points are in Long&Lat format which is not good, I need it in the same format I create the polygon: [Lat&Long]

I thought about working with `public function getPolygonAttribute($value)` on the laravel side but still I need help here.

Thank you in advance,
Lior.

**Comment by llioor** [comment]
Hi Joseph @grimzy 
Can you please help me with this one? I'll really appreciate it.
Thanks.

**Comment by llioor** [comment]
Up @grimzy , anyone has an answer please?

**Comment by grimzy** [comment]
When saving a `Point` into a MySQL database it has to be saved using `Point(longitude latitude)` (Well Known Text - WKT). 

In the same manner, but this time for output:
- when encoding a `Point` object to `JSON` the package follows the `GeoJSON` specification where `Point` coordinates definition is `[0 => longitude, 1 => latitude]`
- when encoding a `Point` object to `String` the package follows the WKT specification: `Point(longitude latitude)` - the same as when saving.

I'm not sure how to guide you as I'm not sure how you are planning to use the `Polygon` but my best guess would be for you to loop through the `coordinates array` in the `GeoJSON` and use the coordinates as you please.

PS @llioor: sorry for the late answer!

**Comment by davidpiesse** [comment]
Sounds like it's just that! 
No idea why Lon,Lat is used by so many places when most say Lat,Lon.
Do you input lat,Lon expecting that to persist to the end result but they get flipped?

**Comment by grimzy** [comment]
My best guess is that the specifications are the same when using geographic fields (longitude/latitude) or geometry fields (X/Y).

I decided to define the `Point` constructor as `Point($lat, $lng)` because it felt more intuitive when reading/using it.

**Comment by llioor** [comment]
Hi Guys.. @davidpiesse @grimzy 
Thanks for the answer, I really appreciate it!
The problem is:
1. I create array of `$arrayOfPoints[] = new Point(Lat, Long)`
```
[34.783342, 32.075312],
[34.782876, 32.075323],
[34.782862, 32.074953],
[34.783407, 32.07494],
[34.783342, 32.075312],
```
2. I create the lineString with this array `new LineString($arrayOfPoints);`
3. I crate the polygon with the lineString `new Polygon([$lineString]);`
4. Then I just set it to the Class spatial parameter and I save the class
```
$item = new Item($data);
...
$item->polygon = $this->buildPolygonFromArray($data['polygon']);
$item->save();
```
5. The polygon is been saved automatically on DB in this format:
`'POLYGON((32.075312 34.783342,32.075323 34.782876,32.074953 34.782862,32.07494 34.783407,32.075312 34.783342))',0`

**The problem is when I select the class like:**
```
$item = Item::find(1);
return $item->polygon;
```

This is what I receive:
`{"type":"Polygon","coordinates":[[[32.075312,34.783342],[32.075323,34.782876],[32.074953,34.782862],[32.07494,34.783407],[32.075312,34.783342]]]}`

You can see that the points in `coordinates` are flipped. Long,Lat instead how I saved them Lat,Long...

As I understood from your answer I will need to go over the array and to flip it manually to Lat,Long format? sounds wrong... 
What do you think?

**Comment by davidpiesse** [comment]
Pretty much.

I would suggest as a refactoring exercise using collections for the coord array conversion to polygon.
It should be as simple as switching the [0] and [1] on your coord array when you create the points

**Comment by llioor** [comment]
Hi @davidpiesse ,
Sorry I didn't understand you =\

**Comment by davidpiesse** [comment]
Something like this. (Have not tested)

NOTE - the main important change is from
```php
new Point($point[0], $point[1])
```
to
```php
new Point($point[1], $point[0])
```

```php
private function buildPolygonFromArray($polygon) {
    return new Polygon(
        new LineString(
            collect($polygon['coordinates'][0])->map(function($point){
                return new Point($point[1], $point[0]);
            })->toArray()
        )
    );
}
```

**Comment by llioor** [comment]
@davidpiesse thank you very much!
Polygon wants to get array so this is the right code:

```
private function buildPolygonFromArray($polygon) {
    return new Polygon([ // here open array
        new LineString(
            collect($polygon['coordinates'][0])->map(function($point){
                return new Point($point[1], $point[0]);
            })->toArray()
        )] // here close array
    );
}
```
I still do not agree with `Point($point[1], $point[0]);` because Point __construct() receive ($lat, $lng) so why should I fake it like ($lng, $lat). @grimzy please consider it.

Guys, thank you very much for the help.

**Comment by vahidalvandi** [comment]
why in document you say

` new Point(40.7484404, -73.9878441);	// (lat, lng)`

**Comment by vahidalvandi** [comment]
for fix flip lng,lat use this

https://github.com/vahidalvandi/laravel-mysql-spatial

**Comment by dhcmega** [comment]
> I still do not agree with `Point($point[1], $point[0]);` because Point __construct() receive ($lat, $lng) so why should I fake it like ($lng, $lat). @grimzy please consider it.

I don't like it either, it makes sense though. The only case in which the package uses lat,lng is when creating a point, it reverses it, and then everything works with lng, lat.
Given that when you pull the information from the database it's flipped, you have to flip it again if you want to use Point, because it only receives lat,lng.

I think that having a way to pull from the database the coords as they were inserted would be good.
