### ISSUE TITLE
Question: using geometry fields in Model::firstOrCreate()

### ISSUE THREAD

**Issue by fisharebest** [grimzy/laravel-mysql-spatial#31]
I can insert geometry records using the following code:

```
        $location = new Point($datum->lat, $datum->lon);
        MyModel::firstOrCreate([
            'location' => DB::raw("ST_GeomFromText('" . $location->toWKT() . "')"),
        ]);
```

This seems a little verbose.  Is there a shorter/cleaner way to do this?

**Comment by Synchro** [comment]
According to the docs you can just say:

    $location = new Point($datum->lat, $datum->lon);
    MyModel::firstOrCreate([
        'location' => $location
    ]);

**Comment by fisharebest** [comment]
Thanks!

I did try this, but perhaps I used the wrong `Point` class (there are several in my project).
