### ISSUE TITLE
Proposal: Integrate with Laravel 5.5 spatial fields migrations

### ISSUE THREAD

**Issue by grimzy** [grimzy/laravel-mysql-spatial#32]
It would be nice to use the Laravel 5.5 spatial fields migrations instead of the package migrations:
https://laravel.com/docs/5.5/migrations#columns

**Comment by xfudox** [comment]
I agree with you, I'm making some tests but i keep receiving

> TypeError: [...] {closure}() must be an instance of Grimzy\LaravelMysqlSpatial\Schema\Blueprint, instance of Illuminate\Database\Schema\Blueprint given

It would be fantastic to use Eloquent spatial fields with your SpatialTrait.

**Comment by bkoch31** [comment]
> I agree with you, I'm making some tests but i keep receiving
> 
> > TypeError: [...] {closure}() must be an instance of Grimzy\LaravelMysqlSpatial\Schema\Blueprint, instance of Illuminate\Database\Schema\Blueprint given
> 
> It would be fantastic to use Eloquent spatial fields with your SpatialTrait.

@xfudox did you find a workaround for this? Writing tests with the same error as well.

**Comment by xfudox** [comment]
@bkoch31 I found no official "solution" to this, but looking [here](https://laravel.com/docs/5.7/migrations#creating-columns) you can see Eloquent already support spatial data types like point, so I'm using standard `Blueprint `with grimzy `SpatialTrait` and it gives no errors.

I tought that independently from how I save data to a `point` field, it will sitll be a `point` data, so the `SpatialTrait` will be able to read it correctly.
