### ISSUE TITLE
Point Class not found

### ISSUE THREAD

**Issue by keithgulbro** [grimzy/laravel-mysql-spatial#34]
Hi there,

I ran into an issue when I try to push my data to the database, here is the error I'm receiving:

`Symfony\Component\Debug\Exception\FatalThrowableError: Class &#039;App\Http\Controllers\Point&#039; not found`

Currently using:
Laravel Framework 5.5.28
MySQL Version : 5.6.36

**Migration**

`use Grimzy\LaravelMysqlSpatial\Schema\Blueprint;`

    public function up()
    {
        Schema::create('pins', function (Blueprint $table) {
          $table->point('_geoloc')->nullable();
    }

**Model.php** 
`use Illuminate\Database\Eloquent\Model;`
`use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialTrait;`

`protected $spatialFields = [
        '_geoloc',
    ];`

**Controller.php**
```
namespace App\Http\Controllers;

use App\Pin;
use Illuminate\Http\Request;

class PinController extends Controller {
    public function store(Request $request) {
      $pin = new Pin();
      $pin->_geoloc = new Point(-40.1134343, -43.76543);
      $pin->save();
    }
}
```

Please let me know any ideas you may have, thanks!

**Comment by grimzy** [comment]
**Controller.php**
```
use Grimzy\LaravelMysqlSpatial\Types\Point;
```

**Comment by keithgulbro** [comment]
@grimzy Hi, thanks that fixed my error but now I am noticing that the record inserted into my database looks like this: 

`POINT(-43.76543 -40.1134343)`

but I expected it to become a JSON object inside the database. The reason I'm asking this is because for the project that I'm implementing this in, I'm trying to implement https://www.algolia.com/doc/guides/searching/geo-search/ which requires a database column `_geoloc` that has coordinates in JSON format.

**Comment by JoeCDNA** [comment]
Unfortunately, when using Spatial Types, MySQL doesn't store the the data in a `JSON` string: 
https://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html

You'll have to upgrade your MySQL version and use the `JSON` type or use some kind of `String` type.

**Comment by grimzy** [comment]
Unfortunately, when using Spatial Types, MySQL doesn't store the the data in a JSON string:
https://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html

You'll have to upgrade your MySQL version and use the JSON type or use some kind of String type.

**Comment by keithgulbro** [comment]
@grimzy Thanks for the quick response and feedback, I really appreciate it!
