### ISSUE TITLE
What units this package uses for distance?

### ISSUE THREAD

**Issue by chilio** [grimzy/laravel-mysql-spatial#37]
Km, Meters, Miles ?

**Comment by kevdotbadger** [comment]
It uses MySQL spatial functions, and their docs say metres (https://dev.mysql.com/doc/refman/5.7/en/spatial-convenience-functions.html).

I mixed this library with https://github.com/PhpUnitsOfMeasure/php-units-of-measure for doing all my conversions when data isn't stored in metres.

**Comment by grimzy** [comment]
@kevdotbadger is right: meters.

**Comment by grimzy** [comment]
It's also important to note that [`ST_Distance()`](https://dev.mysql.com/doc/refman/5.7/en/spatial-relation-functions-object-shapes.html#function_st-distance) is a distance calculation between 2 shapes on a flat plane.
For example, the formula for the distance between two points (X<sub>1</sub>, Y<sub>1</sub>) and (X<sub>2</sub>, Y<sub>2</sub>) is:
distance = squareRoot ( (X<sub>2</sub>−X<sub>1</sub>)<sup>2</sup>+(Y<sub>2</sub>−Y<sub>1</sub>)<sup>2</sup> )

In general, `ST_Distance()` doesn't perform any unit conversion and therefore returns a distance in the same unit used by the coordinate system used input in that function.
