### ISSUE TITLE
lat/lng vs lng/lat, should flip stored coordinates in database?

### ISSUE THREAD

**Issue by m2sh** [grimzy/laravel-mysql-spatial#38]
Hi
We stored coordinates in `Point(lat lng)` format. Now when I want to use this package the result of `getLat()` and `getLng()` is incorrect. 
I think we have two solution : 
- Flip all coordinate in MySQL database using `Update` SQL query and use this package.
- Customize this package to use flip ordered of lat/lng by editing `Point.php` file methods.

I know there are different standards/approaches ([ISO 6709](https://en.wikipedia.org/wiki/ISO_6709), [MySQL Forum](https://forums.mysql.com/read.php?23,209566,209566)). But I don't know which solution is better.
Do you have any suggestion ?

**Comment by grimzy** [comment]
I'm not sure if it fits your need, but you can create your own `PointXY` model extending `Point` and do the changes you need in the constructor and all the other repetitive methods there (sorry about that!). Then use `PointXY` when retrieving the data from your database.

Regarding the standards, this package integrate with MySQL and is attempting to follow the same specification. Also, the [response to the MySQL Forum thread](https://forums.mysql.com/read.php?23,209566,210132#msg-210132) gave sense to my second comment in [#30](https://github.com/grimzy/laravel-mysql-spatial/issues/30#issuecomment-354133743). Thank you!

PS: **We**, you're referring to you and @chilio ? ;)

**Comment by m2sh** [comment]
Thanks for your answer. I flipped coordinates two weeks ago to use your package and currently we are using lon/lng format in our project.

**Comment by vahidalvandi** [comment]
it is very bad !! in document
 new Point(40.7484404, -73.9878441);	// (lat, lng)
why it flip  it ?
