### ISSUE TITLE
Mysql Geo Field Format

### ISSUE THREAD

**Issue by Snowing** [grimzy/laravel-mysql-spatial#47]
So, right now the field parsed using code:
```
 public static function fromWKB($wkb)
    {
        // mysql adds 4 NUL bytes at the start of the binary
        $prefix = "\0\0\0\0";
        if (substr($wkb, 0, strlen($prefix)) == $prefix) {
            $wkb = substr($wkb, strlen($prefix));
        }

        $parser = new Parser(new Factory());

        return $parser->parse($wkb);
    }
```
but mysql field actually stored like  
$srid . $wkb
where length of $srid is 4 bytes

if $srid != 0, there will be error like this
`Parsing failed: Bad endian byte value 230`

Well, for mysql <8.0 there no differences between any value of $srid,
but for Earth coordinates correct one is 4326 (EPSG:4326 - wgs-84)
and difference appears in mysql >=8

At the end, it's, probably, should looks like this:
```
 public static function fromMysqlGeoField($value)
    {
       // $srid = substr($value,0,4); //  
       $wkb = substr($value, 4);
       $parser = new Parser(new Factory());
       return $parser->parse($wkb);
    }
```

**Comment by grimzy** [comment]
Thank you for reporting this.

You're right, the current version of the package doesn't handle SRIDs properly. This integration with MySQL 8 has to be implemented. 

As reported in #54, the implementation should also update how we query the database.
