### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by enourinick** [grimzy/laravel-mysql-spatial#49]
Hi,

refere to `laravel\framework` commit of `Add support for defining a Spatial reference system for a Point column. (code: ddc4e05fc03a8f55a56be2afdce48ba891879d65)`, they add srid to declearation of `point` method.

Due to what I mentioned above, it needs to make point method your Blueprint compatible.

check following error:
```
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column) should be compatible with Illuminate\Database\Schema\Blueprint::point($column, $srid = NULL)
```

**Comment by Dylan-DutchAndBold** [comment]
Shouldn't the whole Blueprint class be dropped, since all the functions are baked into laravel now.

**Comment by grimzy** [comment]
@enourinick @J5Dev, is there more to this issue? Do we need to update the Blueprints for the other spatial fields?

**Comment by grimzy** [comment]
@Dylan-DutchAndBold, we should probably keep the Blueprint for backward compatibility (Laravel < 5.5). Although I agree that for Laravel 5.5+, the Blueprint in this package is not needed.

**Comment by andreshg112** [comment]
Is there a workaround?
I can modify the source code locally but not in production.

**Comment by J5Dev** [comment]
The PR is in, but it seems it hasn't been tagged with a new version yet, just pull dev-master to get the changes.

**Comment by enourinick** [comment]
Check version 2.1.0:
https://github.com/grimzy/laravel-mysql-spatial/releases/tag/2.1.0

**Comment by J5Dev** [comment]
Ahaaa, thanks, wasn't up when the PR went in. Will update our composer file :)
