### ISSUE TITLE
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column)

### ISSUE THREAD

**Issue by levinhne** [grimzy/laravel-mysql-spatial#52]
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column) should be compatible with Illuminate\Database\Schema\Blueprint::point($column, $srid = NULL)

**Comment by J5Dev** [comment]
This is a duplicate of #49 and already has a pull request in.

**Comment by andreshg112** [comment]
Is there a workaround?
I can modify the source code locally but not in production.

**Comment by grimzy** [comment]
@andreshg112, please update your dependency. The change was published in the latest release: `v2.1.0`.

**Comment by andreshg112** [comment]
Thank you, @grimzy!

I noticed it yesterday.
