### ISSUE TITLE
Location and Area should also be listed in $fillable in model

### ISSUE THREAD

**Issue by kheme** [grimzy/laravel-mysql-spatial#57]
I had a problem accessing latitude/longitude using `$place->location->getLng()`.
I noticed that including **location** and **area** in `$fillable` solved the problem.

So, while **location** and **area** are both listed in `$spatialFields`, they should both also be listed in `$fillable`.

**Comment by grimzy** [comment]
What versions of Laravel, Eloquent and Laravel MySQL Spatial are you using?

My understanding is that `$fillable` is used by Eloquent when creating/updating records, not when fetching records.

**Comment by grimzy** [comment]
MySQL 10.1?
You probably mean MariaDB 10.1.
