### ISSUE TITLE
What is the unit of distance in Scope

### ISSUE THREAD

**Issue by jishnu2292** [grimzy/laravel-mysql-spatial#59]
In what unit the value of parameter $distance is given in the available scopes in Spatial analysis functions?

distance($geometryColumn, $geometry, $distance)

**Comment by NicksonYap** [comment]
Sorry for bumping, but when using GPS coordinates, the distance unit seems to be using degrees
I suppose the distance unit follows whatever unit is used in the column (dimension-less)

Correct me if i'm wrong
