### ISSUE TITLE
Can´t use Within - Special analysis functions 

### ISSUE THREAD

**Issue by jonymtfca** [grimzy/laravel-mysql-spatial#60]
I´m trying to test the within function to check if a point is inside a defined polygon. 

Here´s the code i´m using:

```
$place = Place::first();
        $polygon = new Polygon([new LineString([
            new Point(40.74894149554006, -73.98615270853043),
            new Point(40.74848633046773, -73.98648262023926),
            new Point(40.747925497790725, -73.9851602911949),
            new Point(40.74837050671544, -73.98482501506805),
            new Point(40.74894149554006, -73.98615270853043)
        ])]);

        return Place::within('location', $polygon) ;
```

'location' is the column on my table -> ($table->point('location');)

When i run the within function, it keeps giving me this error: 

> Object of class Grimzy\LaravelMysqlSpatial\Eloquent\Builder could not be converted to string

Am i doing something wrong?

**Comment by grimzy** [comment]
Change:
```return Place::within('location', $polygon);```
to:
``` return Place::within('location', $polygon)->get();```
Should return a `Collection` with all your `Place` objects within the `Polygon`.

**Comment by jonymtfca** [comment]
It worked, thank you very much 👍 

Keep the good job
