### ISSUE TITLE
Search by multiple polygons inside a polygon

### ISSUE THREAD

**Issue by jonymtfca** [grimzy/laravel-mysql-spatial#62]
Hi,

I´m building a application where the user can insert a point, line or polygon. Since i have to search by drawing a polygon on the map, i decided to save all of the above as polygons (because this way i only need one index, and the point or line can be null), as shown in the example below:

POINT(-8.534297 37.115448) -> POLYGON((-8.534297 37.115448,-8.534297 37.115448,-8.534297 37.115448,-8.534297 37.115448))
LINESTRING(-8.542011 37.117322,-8.540262 37.11674) -> POLYGON((-8.542011 37.117322,-8.540262 37.11674,-8.542011 37.117322,-8.542011 37.117322))

So, my question is: Is there a search method where i give the search (drawed) polygon to the function, and it returns all the polygons found inside (points and lines, converted to polygons be me).

I think i tried all of the functions you specify in the documentation and none of them seems to do what i need. Am i missing something?

Thanks in advance

**Comment by grimzy** [comment]
Have you tried `scopeWithin()`/`ST_within()`?
- https://dev.mysql.com/doc/refman/8.0/en/spatial-relation-functions-object-shapes.html#function_st-within

Or  maybe `scopeContains()`/`ST_contains()` ? 
- https://dev.mysql.com/doc/refman/8.0/en/spatial-relation-functions-object-shapes.html#function_st-contains

https://github.com/grimzy/laravel-mysql-spatial#scopes-spatial-analysis-functions
