### ISSUE TITLE
orderByDistance()

### ISSUE THREAD

**Issue by robjbrain** [grimzy/laravel-mysql-spatial#64]
I thought i'd put this here for anyone else that wanted it.

I wanted to orderByDistance and it was as simple as:

```php
public function scopeOrderByDistance($query, $geometryColumn, $geometry)
    {
        $this->isColumnAllowed($geometryColumn);

        $query->orderByRaw("st_distance(`$geometryColumn`, ST_GeomFromText(?))", [
            $geometry->toWkt()
        ]);

        return $query;
    }
```

Presumably you can add these scopes for the other columns as well.

**Comment by NicksonYap** [comment]
Great reference for running other spatial queries! Thanks!

**Comment by lostfocus** [comment]
I was looking for that, thank you!

**Comment by iSWORD** [comment]
Very helpful, thanks @robjbrain 

This should be merged into the trait @grimzy

**Comment by grimzy** [comment]
@robjbrain Thank you! Rolling out a new version with this scope soon.

Better late than never?
