### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by IgorBondarenk** [grimzy/laravel-mysql-spatial#68]
Next Illuminate\Database\QueryException: SQLSTATE[22003]: Numeric value out of range: 1416 Cannot get geometry object from data you send to the GEOMETRY field (SQL: update `parkings` set `place_coordinates` = {"type":"LineString","coordinates":[[37.6946685,55.7900313],[37.6948428,55.7901565]]}, `updated_at` = 2018-11-20 05:04:52 where `id` = 1) in /home/vagrant/parkings/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664

I think I have problems with Laravel builder, How can I fix it?

**Comment by IgorBondarenk** [comment]
I solved it with a raw query to the database.

**Comment by Entryist** [comment]
I've gotten this error when I forgot to add `use SpatialTrait` and `$spatialFields` to the model.
