### ISSUE TITLE
Is it possible to query using 2 polygons?

### ISSUE THREAD

**Issue by jericopulvera** [grimzy/laravel-mysql-spatial#75]
```
  $data = Imagery::with('satellite')
                ->intersects('geometry', $geometry)
```

This is my current query and it works.

Is it possible to intersect using 2 polygon?

**Comment by grimzy** [comment]
More details please? What's the possible implementation?

**Comment by jericopulvera** [comment]
@grimzy Sorry about this I have really forgotten the problem that I am trying to solve here long ago.
