### ISSUE TITLE
grabbing distance value when querying/sorting 

### ISSUE THREAD

**Issue by acidjazz** [grimzy/laravel-mysql-spatial#77]
i'd like to get the distance value of each result as they are returned using the distance and/or distanceSphere scopes.

is this possible to do at all? is it easy to add?

**Comment by lukecurtis93** [comment]
did you ever work this one out?

**Comment by acidjazz** [comment]
@lukecurtis93 not yet! still looking and asking around! i'll be sure to update this issue if i do

**Comment by ruledio** [comment]
just tried this using the method distanceValue or distanceSphereValue and it seems to work (it's not in the docs tho) found it by looking at the tests.

**Comment by acidjazz** [comment]
@ruledio can you please supply an example?

**Comment by ruledio** [comment]
Nice and simple really, just chnage distanceSphere to distanceSphereValue

```
$user = User::distanceSphereValue('location', new Point('0.916687', '51.890146'), 20)->first();
```

You can then access the distance with 

```
dd($user->distance);
```

**Comment by vesper8** [comment]
Thank you for sharing this @ruledio, however this is one problem with the code above.

`distanceSphereValue`, unlike `distanceSphere`, does not accept a 3rd parameter specifying the range (in meters by the way, so 20 would be an awfully small range). 

`distanceSphere`: https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/Eloquent/SpatialTrait.php#L173

`distanceSphereValue`: https://github.com/grimzy/laravel-mysql-spatial/blob/master/src/Eloquent/SpatialTrait.php#L198

Using `distanceSphereValue` thus returns ALL results.

I don't think you can efficiently filter results within a range without making a PR or creating your own scope. But doing this you can achieve the desired filtering although this is done after-the-fact using collection methods so it must not be very performant on a large resultset:

```
        $model->distanceSphereValue('location_column', $point)
        ->get()
        ->where('distance', '<=', $distanceInMeters)
        ->sortBy('distance');
```

**Comment by vesper8** [comment]
I added a new custom scope which seems to do what I want and performs well, not sure if there's a more efficient way to write this query:

```
<?php

namespace App\Traits;

trait CustomSpatialTrait
{
    public function scopeDistanceSphereValueWithin($query, $geometryColumn, $geometry, $distance)
    {
        $this->isColumnAllowed($geometryColumn);

        $columns = $query->getQuery()->columns;

        if (!$columns) {
            $query->select('*');
        }

        $query->selectRaw("st_distance_sphere(`$geometryColumn`, ST_GeomFromText(?)) as distance", [
            $geometry->toWkt(),
        ])
        ->whereRaw("st_distance_sphere(`$geometryColumn`, ST_GeomFromText(?)) <= ?", [
            $geometry->toWkt(),
            $distance,
        ]);
    }
}
```

**Comment by joshhudnall** [comment]
You can always combine scopes to achieve what you want: 

`$user = User::distanceValue('location', new Point('0.916687', '51.890146'))->distanceSphere('location', new Point('0.916687', '51.890146'), 20)->first();`
