### ISSUE TITLE
Invalid parameter value: 3037 Invalid GIS data provided to function st_geometryfromtext.

### ISSUE THREAD

**Issue by jpaulolxm** [grimzy/laravel-mysql-spatial#84]
I get this error message when I do a simple insert to a Point field:
`SQLSTATE[22023]: Invalid parameter value: 3037 Invalid GIS data provided to function st_geometryfromtext. (SQL: insert into `servicos__clientes__location` (`id_user`, `id_servico_cliente`, `location`, `created_at`) values (399, 2673, ST_GeomFromText(POINT(-60,0090723 -3,0886383)), 2019-04-05 19:00:51))`

My code

`<?php

namespace NGestor\ApiFieldService\Http\Controllers\Location;

use Grimzy\LaravelMysqlSpatial\Types\Point;
use NGestor\ApiFieldService\Http\Requests\Location\SetClientePositionFormRequest;
use NGestor\ApiFieldService\Models\Location\ServicoClienteLocation;
use NGestor\ApiFieldService\Models\Service\Index\Servicos;
use NGestor\ApiFieldService\Repository\Servico\Cliente\ClienteLocation;
use NGestor\Core\Http\Controllers\Controller;

class ClienteLocationController extends Controller
{
    public function setPosition(SetClientePositionFormRequest $request)
    {
        try{

            $servico = Servicos::find($request->idServico);

            $locate = new ServicoClienteLocation();

            $locate->id_user             = $request->idUser;
            $locate->id_servico_cliente  = $servico->id_servico_cliente;
            $locate->location            = new Point($request->lat, $request->lng);
            $locate->save();

        }catch (\Exception $exception)
        {
            logger("ClienteLocationController -> setPosition ");
            logger($exception->getMessage());

            return [
                'sucesso' => false,
                'msg'     => $exception->getMessage(),
            ];
        }

        return ['sucesso' => true];
    }
}`

**Comment by seinoxygen** [comment]
I'm getting it too.

**Comment by AlextheYounga** [comment]
@seinoxygen 

Thanks, that solved it for me, last point has to match the first point to close the polygon.

**Comment by seinoxygen** [comment]
Exactly

**Comment by grimzy** [comment]
For the sake of completeness, before closing the issue, here's the MySQL documentation about the Polygon: https://dev.mysql.com/doc/refman/8.0/en/gis-class-polygon.html. The Polygon has other assertions that would return a similar error.

**Comment by jamesctl** [comment]
> @seinoxygen
> 
> Thanks, that solved it for me, last point has to match the first point to close the polygon.

thank you so much for your answer, I spent many time to find the way how to fix it. it's work for me. thank you
