### ISSUE TITLE
not working in PHPUnit testing

### ISSUE THREAD

**Issue by mfs-gourab** [grimzy/laravel-mysql-spatial#97]
it's working perfectly on the web. But in PHPUnit testing, it's showing an error.

) Tests\Feature\DestinationTest::destination_addition Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such function: ST_GeomFromText (SQL: insert into "destinations" ("name", "url", "about", "address", "location", "image", "updated_at", "created_at") values (sddsds, sddsds, sfdsfs sdfds sdfsd, dsfds dsfds, ST_GeomFromText(POINT(30.33 20.22)), destination/0PKOpauAuF1wB8cvXz6UQiwT2LXACUlWx6J5eeAI.jpeg, 2019-08-16 06:46:26, 2019-08-16 06:46:26))

**Comment by grimzy** [comment]
Did you get this while testing against SQLite?
This package only works with MySQL.

**Comment by mfs-gourab** [comment]
Yes, I am getting the error in SQLite.
In MySQL, it's working fine.
